"""10개 이력서 Ground Truth 정의"""

GROUND_TRUTHS = {
    "resume_01": {
        "career_count": 3,
        "companies": [
            {"name_keywords": ["스마트솔루션즈"], "is_private": False, "currently_employed": True,
             "start": "2021-09", "employment_type": "정규직", "salary_keyword": "8,500"},
            {"name_keywords": ["네이버", "Naver"], "is_private": False,
             "start": "2018-03", "end": "2021-08", "reason_keyword": "커리어"},
            {"is_private": True, "start": "2016-07", "end": "2018-02",
             "employment_type": "계약직", "reason_keyword": "계약"},
        ],
        "activity_count": 2,
        "activities_keywords": ["삼성SDS", "머신러닝"],
        "overseas_count": 1, "overseas_keywords": ["교환학생", "미국", "Berkeley"],
        "language_count": 3, "lang_keywords": ["TOEIC", "935", "JLPT"],
        "certificate_count": 2, "cert_keywords": ["정보처리기사", "AWS"],
        "award_count": 1, "award_keywords": ["해커톤"],
        "military": {"status": "군필", "branch": "육군", "rank": "병장"},
        "sns_count": 2, "sns_keywords": ["github", "linkedin"],
    },
    "resume_02": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["카카오", "Kakao"], "is_private": False, "currently_employed": True,
             "start": "2022-01", "employment_type": "정규직"},
            {"name_keywords": ["쿠팡", "Coupang"], "is_private": False,
             "start": "2019-06", "end": "2021-12", "reason_keyword": "도메인"},
        ],
        "activity_count": 1, "activities_keywords": ["우아한테크코스", "부트캠프"],
        "overseas_count": 1, "overseas_keywords": ["워킹홀리데이", "호주"],
        "language_count": 2, "lang_keywords": ["TOEIC", "Speaking"],
        "certificate_count": 2, "cert_keywords": ["정보처리기사", "SQLD"],
        "award_count": 1, "award_keywords": ["Best Engineer", "쿠팡"],
        "military": {"status": "해당없음"},
        "sns_count": 2, "sns_keywords": ["github", "velog"],
    },
    "resume_03": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["삼성전자"], "is_private": False, "currently_employed": True,
             "start": "2015-03", "employment_type": "정규직", "salary_keyword": "1억"},
            {"name_keywords": ["LG전자"], "is_private": False,
             "start": "2012-07", "end": "2015-02", "reason_keyword": "반도체"},
        ],
        "activity_count": 1, "activities_keywords": ["삼성", "아카데미"],
        "overseas_count": 1, "overseas_keywords": ["유학", "미국", "Georgia"],
        "language_count": 4, "lang_keywords": ["TOEIC", "890", "HSK"],
        "certificate_count": 2, "cert_keywords": ["반도체", "PMP"],
        "award_count": 2, "award_keywords": ["사장상", "우수논문"],
        "military": {"status": "군필", "branch": "공군", "rank": "병장"},
        "sns_count": 1, "sns_keywords": ["linkedin"],
    },
    "resume_04": {
        "career_count": 3,
        "companies": [
            {"name_keywords": ["마켓컬리", "컬리"], "is_private": False, "currently_employed": True,
             "start": "2023-02", "employment_type": "정규직"},
            {"is_private": True, "start": "2021-01", "end": "2023-01",
             "reason_keyword": "이커머스"},
            {"name_keywords": ["위즈돔"], "is_private": False,
             "start": "2020-07", "end": "2020-12", "employment_type": "계약직"},
        ],
        "activity_count": 2, "activities_keywords": ["BOAZ", "데이터"],
        "overseas_count": 0, "overseas_keywords": [],
        "language_count": 3, "lang_keywords": ["TOEIC", "820", "OPIc"],
        "certificate_count": 3, "cert_keywords": ["ADsP", "SQLD", "Google Analytics"],
        "award_count": 1, "award_keywords": ["BOAZ", "우수상"],
        "military": {"status": "해당없음"},
        "sns_count": 2, "sns_keywords": ["github", "kaggle"],
    },
    "resume_05": {
        "career_count": 4,
        "companies": [
            {"name_keywords": ["토스", "Viva Republica"], "is_private": False, "currently_employed": True,
             "start": "2021-04", "salary_keyword": "1억"},
            {"name_keywords": ["라인", "LINE"], "is_private": False,
             "start": "2017-09", "end": "2021-03", "reason_keyword": "핀테크"},
            {"name_keywords": ["NHN"], "is_private": False,
             "start": "2014-03", "end": "2017-08", "reason_keyword": "글로벌"},
            {"is_private": True, "start": "2012-09", "end": "2014-02",
             "reason_keyword": "대기업"},
        ],
        "activity_count": 1, "activities_keywords": ["오픈소스", "컨트리뷰톤"],
        "overseas_count": 1, "overseas_keywords": ["어학연수", "필리핀"],
        "language_count": 4, "lang_keywords": ["TOEIC", "870", "JLPT", "N1"],
        "certificate_count": 2, "cert_keywords": ["정보처리기사", "CKA"],
        "award_count": 2, "award_keywords": ["Tech Award", "컨트리뷰톤"],
        "military": {"status": "군필", "branch": "해군", "rank": "상병"},
        "sns_count": 3, "sns_keywords": ["github", "linkedin", "dev"],
    },
    "resume_06": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["당근마켓", "당근"], "is_private": False, "currently_employed": True,
             "start": "2022-06", "employment_type": "정규직"},
            {"is_private": True, "start": "2020-03", "end": "2022-05",
             "reason_keyword": "규모"},
        ],
        "activity_count": 2, "activities_keywords": ["코드스테이츠", "멋쟁이사자"],
        "overseas_count": 0, "overseas_keywords": [],
        "language_count": 2, "lang_keywords": ["TOEIC", "780"],
        "certificate_count": 2, "cert_keywords": ["웹디자인", "GAIQ"],
        "award_count": 0, "award_keywords": [],
        "military": {"status": "해당없음"},
        "sns_count": 2, "sns_keywords": ["github", "tistory"],
    },
    "resume_07": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["현대자동차", "현대"], "is_private": False, "currently_employed": True,
             "start": "2019-01", "salary_keyword": "1억"},
            {"name_keywords": ["현대모비스"], "is_private": False,
             "start": "2015-07", "end": "2018-12", "reason_keyword": "자율주행"},
        ],
        "activity_count": 1, "activities_keywords": ["NVIDIA", "Deep Learning"],
        "overseas_count": 1, "overseas_keywords": ["유학", "독일", "RWTH"],
        "language_count": 4, "lang_keywords": ["TOEIC", "910", "TestDaF"],
        "certificate_count": 2, "cert_keywords": ["자동차정비", "ISO 26262"],
        "award_count": 2, "award_keywords": ["사장상", "CES"],
        "military": {"status": "군필", "branch": "육군", "rank": "병장"},
        "sns_count": 1, "sns_keywords": ["linkedin"],
    },
    "resume_08": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["네이버웹툰", "웹툰"], "is_private": False, "currently_employed": True,
             "start": "2021-08", "salary_keyword": "7,500"},
            {"is_private": True, "start": "2019-03", "end": "2021-07",
             "reason_keyword": "글로벌"},
        ],
        "activity_count": 1, "activities_keywords": ["Apple", "POSTECH"],
        "overseas_count": 1, "overseas_keywords": ["교환학생", "일본", "도쿄"],
        "language_count": 4, "lang_keywords": ["TOEIC", "905", "JLPT", "N1"],
        "certificate_count": 2, "cert_keywords": ["정보처리기사", "Apple"],
        "award_count": 1, "award_keywords": ["WWDC", "Apple"],
        "military": {"status": "해당없음"},
        "sns_count": 2, "sns_keywords": ["github", "linkedin"],
    },
    "resume_09": {
        "career_count": 2,
        "companies": [
            {"name_keywords": ["안랩", "AhnLab"], "is_private": False, "currently_employed": True,
             "start": "2020-01", "salary_keyword": "7,800"},
            {"is_private": True, "start": "2018-03", "end": "2019-12",
             "employment_type": "계약직", "reason_keyword": "보안"},
        ],
        "activity_count": 2, "activities_keywords": ["BOB", "사이버"],
        "overseas_count": 0, "overseas_keywords": [],
        "language_count": 2, "lang_keywords": ["TOEIC", "850"],
        "certificate_count": 3, "cert_keywords": ["정보보안기사", "OSCP", "CEH"],
        "award_count": 2, "award_keywords": ["DEF CON", "BOB"],
        "military": {"status": "군필", "branch": "육군", "rank": "병장"},
        "sns_count": 2, "sns_keywords": ["github", "tistory"],
    },
    "resume_10": {
        "career_count": 3,
        "companies": [
            {"name_keywords": ["배달의민족", "우아한형제들", "배민"], "is_private": False,
             "currently_employed": True, "start": "2022-09", "salary_keyword": "8,000"},
            {"name_keywords": ["토스페이먼츠", "토스"], "is_private": False,
             "start": "2020-06", "end": "2022-08", "reason_keyword": "PM"},
            {"is_private": True, "start": "2018-09", "end": "2020-05",
             "reason_keyword": "핀테크"},
        ],
        "activity_count": 2, "activities_keywords": ["네이버", "프로덕트"],
        "overseas_count": 1, "overseas_keywords": ["교환학생", "싱가포르", "NUS"],
        "language_count": 3, "lang_keywords": ["TOEIC", "940", "OPIc"],
        "certificate_count": 2, "cert_keywords": ["UXPM", "CPPM"],
        "award_count": 2, "award_keywords": ["해커톤", "Slash"],
        "military": {"status": "해당없음"},
        "sns_count": 2, "sns_keywords": ["linkedin", "brunch"],
    },
}
